use [vksbgxbd_encuesta]
GO
CREATE TABLE dbo.ENB_PREGUNTA (
ID_PREGUNTA INT NOT NULL,
DESCRIPCION_PREGUNTA VARCHAR(500) NOT NULL,
ACTIVA_S_N BIT NOT NULL,
CONSTRAINT  PK_PREGUNTA PRIMARY KEY CLUSTERED (ID_PREGUNTA)
)
GO
CREATE TABLE dbo.ENB_ARCHIVOS_X_PREGUNTA (
ID_ARCHIVO_X_PREGUNTA INT NOT NULL IDENTITY(1,1),
NOMBRE_ARCHIVO VARCHAR(150) NOT NULL,
RUTA_ARCHIVO VARCHAR(150) NOT NULL,
ID_PREGUNTA INT NOT NULL
CONSTRAINT  PK_ARCHIVOS_X_PREGUNTA PRIMARY KEY CLUSTERED (ID_ARCHIVO_X_PREGUNTA),
CONSTRAINT FK_ARCHIVOS_X_PREGUNTA FOREIGN KEY (ID_PREGUNTA)     
    REFERENCES dbo.ENB_PREGUNTA (ID_PREGUNTA)     
    ON DELETE CASCADE    
    ON UPDATE CASCADE    
)
CREATE TABLE dbo.ENH_RESPUESTA_X_PREGUNTA(
ID_RESPUESTA_X_PREGUNTA INT NOT NULL IDENTITY(1,1),
ID_PREGUNTA INT NOT NULL, --INTEGRIDAD REFERENCIAL CON LA TABLA ENB_PREGUNTA
LOGIN_USUARIO VARCHAR (50) NOT NULL,--INTERIDAD REFERENCIAL CON LA TABLA DE USUARIO 
FECHA_RESPUESTA DATETIME NOT NULL,
CUMPLE_S_N BIT NOT NULL, --SI CUMPLE ES UN PUNTAJE SI NO CUMPLE ES OTRO
APLICA_S_N BIT NOT NULL,-- SI APLICA QUE JUSTIFICA
JUSTIFICA_APLICA_S VARCHAR(150) NULL,
USUARIO_VE_ARCHIVO BIT NOT NULL DEFAULT(0),--INDICA SI EL USUARIO QUE DILIGENCIO LA PREGUNTA PUEDE VER SUS ARCHIVOS
CONSTRAINT  PK_RESPUESTA_X_PREGUNTA PRIMARY KEY CLUSTERED (ID_RESPUESTA_X_PREGUNTA),
CONSTRAINT FK_RESPUESTA_X_PREGUNTA FOREIGN KEY (ID_PREGUNTA)     
    REFERENCES dbo.ENB_PREGUNTA (ID_PREGUNTA)     
    ON DELETE CASCADE    
    ON UPDATE CASCADE  
)